use client-id header for device header and cookie id
castle/castle-php pull request #19
Opened 2017-07-05 13:18 UTC by lluft

2017-07-05 18:38 UTC, wallin requested changes

2017-07-05 18:38 UTC, wallin commented on lib/Castle/Request.php
> +      return empty($cid) ? '' : $cid;
This logic need to be kept in order for cURL to not strip the header. See previous PR by @nullaus

2017-07-06 12:58 UTC, lluft commented
@wallin addressed your comment

2017-07-06 18:27 UTC, wallin requested changes

2017-07-06 18:27 UTC, wallin commented on lib/Castle/CookieStore.php
> +    return true;
This doesn't seem necessary

2017-07-06 18:27 UTC, wallin commented on test/CookieStore.php
> +    return true;
Same here

2017-07-07 11:05 UTC, lluft commented
@wallin those were debugging leftovers. Good catch!

2017-07-12 12:56 UTC, merged